### ISSUE TITLE
After Update HLTB still not shwon

### ISSUE THREAD

**Issue by possum-enjoyer** [SDH-Stewardship/hltb-for-deck#6]
After updating to 1.4.3 with the fix, hltb is still not shown for any game. Neither a cache clear nor a reinstall did fix it. 

Tested with:

decky version 2.12.3 
Hltb-for-deck 1.4.3

Edit: closing this issue, 3 consecutive restarts of the steam deck did fix it for some reason.

**Comment by boivinx7** [comment]
Have the same issue and no amount of restarts fixed it

**Comment by SiTWulf** [comment]
Same for me, not fixed
